# config.yaml
# Subject name
subject_name: 'subject_name'

# Camera identification
pi_identifier: 'rpi_name'

# Camera settings
camera:
  brightness: 50
  contrast: 50
  resolution:
    width: 2304
    height: 1296
  frame_format: 'YUV420'
  lens:
    position: 4
  frame_duration_limits: [100000, 100000]
  bitrate: 1000000

# Recording settings
recording:
  chunk_length: 3600  # seconds

# Storage settings
paths:
  video_save_path: '/home/lowelllab/Videos'
  log_save_path: '/home/lowelllab/Videos'

# Cloud storage settings
cloud:
  rclone_config: 'lowelllab:rpi_name'
