# config.yaml

# Subject name
subject_name: 'subject_name'

# Camera identification
pi_identifier: 'rpi_name'

# Camera settings
camera:
  # Basic settings
  brightness: 0.0  # Range: -1.0 to 1.0
  contrast: 1.5   # Range: 0.0 to 32.0
  saturation: 0.0  # Range: 0.0 to 32.0, set to 0 for grayscale
  sharpness: 4.0   # Range: 0.0 to 16.0
  
  # Resolution
  resolution:
    width: 2304
    height: 1296
  
  # Format and exposure
  frame_format: 'YUV420'
  frame_duration_limits: [33333, 120000]  # Updated to match actual camera limits
  
  # Lens settings
  lens:
    position: 4.0  # Range: 0.0 to 32.0
  
  # Additional controls
  analog_gain: 1.0      # Range: 1.0 to 16.0
  exposure_value: 0.0   # Range: -8.0 to 8.0
  noise_reduction: 3    # Range: 0 to 4 (2 = medium quality)
  
  # Encoding
  bitrate: 1000000

# Recording settings
recording:
  chunk_length: 3600  # seconds

# Storage settings
paths:
  video_save_path: '/home/lowelllab/Videos'
  log_save_path: '/home/lowelllab/Videos'

# Cloud storage settings
cloud:
  rclone_config: 'lowelllab:rpi_name'